### ISSUE TITLE
[Admin][Notification] We are not pulling the full list when show more is clicked

### ISSUE THREAD

**Issue by upliftdawah** [upliftdawah/UpliftdawahDocs#11]
When show more is clicked for "New Shahadas" and "Unattended muslims" we are not pulling the full list. Please refer to this link for how to pull the full list: https://github.com/upliftdawah/UpliftdawahDocs#notificationhome-page-apis

**Comment by MuhammadSarimBader** [comment]
Full list is taking to their respective screens from where these notifications actually belongs.

**Comment by upliftdawah** [comment]
I don't know what you mean? the show more option is supposed to show all items, right now it is fixed to 5 items, see the link above for how to get the full list.

**Comment by upliftdawah** [comment]
verified
