### ISSUE TITLE
[Admin][Notification] Unattended New muslims row text

### ISSUE THREAD

**Issue by upliftdawah** [upliftdawah/UpliftdawahDocs#15]
Right now it is showing "Assign a volunteer to \<name\>" instead it should be "\<name\> needs attention, last contacted: <never|Xds ago>" Use the last_contacted field to calculate this duration

**Comment by MuhammadSarimBader** [comment]
I have just put needs Attention to "name" Getting empty string in last contacted

**Comment by upliftdawah** [comment]
last contacted can be null or an integer, if you receiving string then let me know of file an issue. Please recheck the text format above as git hub was hiding \<name\> tag earlier as it wasn't escaped.

**Comment by MuhammadSarimBader** [comment]
fixed

**Comment by upliftdawah** [comment]
All is fixed except that the text is reversed. It should be "\<name\> needs attention" instead of "Needs attention to \<name\>"

**Comment by upliftdawah** [comment]
verified
