### ISSUE TITLE
[General] Hide keyboard when outside of the textbox is clicked

### ISSUE THREAD

**Issue by upliftdawah** [upliftdawah/UpliftdawahDocs#2]
We should audit all screens to make sure that there is a way to close the keyboard. On some screens when a text field is selected the keyboard opens up which hides the submit button since the keyboard doesn't hide it becomes frustrating to use that screen. For example, on the edit profile screen, the only way to hide keyboard is to select the phone number field which changes the keyboard to numeric pad and then close it. We should either have close button on the keyboard or when the focus is out of the text field we should auto close it.

**Comment by MuhammadSarimBader** [comment]
For textfields to hide keyboard iOS have default return button. Otherwise I will have to put a tap gesture on overall parent view that sometimes gets buggy and collide with other UIGestures.

**Comment by upliftdawah** [comment]
Can we enable it? if we see it collides with other gestures we can disable it

**Comment by upliftdawah** [comment]
verified
