### ISSUE TITLE
[General] What is the text in the backgroud

### ISSUE THREAD

**Issue by upliftdawah** [upliftdawah/UpliftdawahDocs#21]
See the screenshot below. This is for user detail screen. Please get it removed, and also check other screens if this text is visible.

![2FADEAC6-1ACF-4CDE-A350-38B0AA126803](https://user-images.githubusercontent.com/61668427/78324304-30bca600-7529-11ea-9bfd-142c902f06a1.png)

**Comment by MuhammadSarimBader** [comment]
We need to buy a background image or you can provide any islamic beautiful image that could replace this image you can even take a photo from your phone.

**Comment by MuhammadSarimBader** [comment]
I have edited and fix this issue but we cannot keep using this image we need to purchase some good picture

**Comment by upliftdawah** [comment]
It is too late to change anything. If you have fixed it, we are good

**Comment by upliftdawah** [comment]
pending verification

**Comment by upliftdawah** [comment]
verified
