### ISSUE TITLE
[Admin][New Muslim Details] Replace the DP icon with Color box

### ISSUE THREAD

**Issue by upliftdawah** [upliftdawah/UpliftdawahDocs#24]
On this screen we are showing the image box with the human head sketch, which gives false impression that the app allows uploading the picture. We should replace it with the box we are showing on the listing screens with color and name initials.

**Comment by MuhammadSarimBader** [comment]
I did it but it is so large that the color effect was really unpleasant to the design

**Comment by upliftdawah** [comment]
not needed
