### ISSUE TITLE
[Admin][New Muslims Details] Display last contacted field

### ISSUE THREAD

**Issue by upliftdawah** [upliftdawah/UpliftdawahDocs#25]
We should display last contacted field as below.
if last_contacted == null:
   Show "Not yet contacted" in red color
if last_contacted is less than 30 days:
  Show "Last contacted X days ago" in green color
if last_contacted is 2 months or more:
  Show "Last contacted X months ago" in red color
if last_contacted is between 1 and 2 months:
  Show "Last contacted X days ago" in yellow color

**Comment by MuhammadSarimBader** [comment]
fixed Case handling took a lot of time

**Comment by upliftdawah** [comment]
verified
