### ISSUE TITLE
[Admin][Member Info] Accept/Reject buttons are always there

### ISSUE THREAD

**Issue by upliftdawah** [upliftdawah/UpliftdawahDocs#27]
We should show buttons appropriately based on user's status. All buttons should have a confirmation box before request is submitted.
If user is Active:
  Show Remove/Ban button -> should set the status to Inactive
If user is InActive:
  Show Activate button -> should set the status to Active
if user is Unclaimed:
  Show Remove/Ban button -> should set the status to Inactive
If user is Unapproved:
  Show Approve and Reject buttons -> approve should set status to Active and Reject should status to Inactive

**Comment by MuhammadSarimBader** [comment]
fixed

**Comment by upliftdawah** [comment]
verified
