### ISSUE TITLE
[User details] Cut the background from the top

### ISSUE THREAD

**Issue by upliftdawah** [upliftdawah/UpliftdawahDocs#28]
Right now. we are showing too much of the top banner. We should cut it down a bit (as shown in the second screenshot below) so that the call and message buttons are visible when the screen is opened. Right now these two buttons are not visible due to the top banner being too big so user can easily miss them.

![C70BB4BB-5078-4C09-9D92-8225F6A97FA3](https://user-images.githubusercontent.com/61668427/78325724-5481eb00-752d-11ea-912a-812b5a13c3da.png)

![E04C63D2-6DFC-4F79-8531-35D5756E0DA5](https://user-images.githubusercontent.com/61668427/78325872-c65a3480-752d-11ea-90c6-57463e3e799e.png)

**Comment by MuhammadSarimBader** [comment]
fixed

**Comment by upliftdawah** [comment]
pending verification

**Comment by upliftdawah** [comment]
verified
