### ISSUE TITLE
[Member Info] Fix 'Other' role text

### ISSUE THREAD

**Issue by upliftdawah** [upliftdawah/UpliftdawahDocs#29]
Right now we are Showing 'Other Muslim', we should change it to just 'Other'

**Comment by MuhammadSarimBader** [comment]
Fixed

**Comment by upliftdawah** [comment]
pending verification

**Comment by upliftdawah** [comment]
pending verification

**Comment by upliftdawah** [comment]
verified. The text is "Dawah worker" which is correct
