### ISSUE TITLE
[Admin][Volunteer List] What 3 dots on right side of each row

### ISSUE THREAD

**Issue by upliftdawah** [upliftdawah/UpliftdawahDocs#31]
We should hide these 3 dots, it gives wrong impression that there is an option on clicking 3 dots

**Comment by MuhammadSarimBader** [comment]
It shows that these list items has something inside or clickable

**Comment by upliftdawah** [comment]
There is only one operation on this row, which is when you click the name. I guess it is unnecessary, please remove it.

**Comment by MuhammadSarimBader** [comment]
fixed

**Comment by upliftdawah** [comment]
verified
