### ISSUE TITLE
[Admin][New Muslim Details] Show appropriate text for assign volunteer button

### ISSUE THREAD

**Issue by upliftdawah** [upliftdawah/UpliftdawahDocs#35]
Right now we are showing "Assign Volunteer" button for all rows instead we should show "View Mentors" when has_mentors == true else show "Assign Mentors"

**Comment by MuhammadSarimBader** [comment]
I will hide the assign volunteer button for those who is already assigned but adding feature for view mentors will add more use cases and another new requirement.

**Comment by MuhammadSarimBader** [comment]
Need to update api for new muslims

**Comment by upliftdawah** [comment]
Which API? Bhai I think we have talk about this so many times. View mentors and assign mentors screen is the same, you just need to add multiple select instead of single selection and show the preselected ones at the top.

**Comment by upliftdawah** [comment]
verified
