### ISSUE TITLE
[Admin][View Ticket] There is no way to see who submitted the ticket

### ISSUE THREAD

**Issue by upliftdawah** [upliftdawah/UpliftdawahDocs#38]
We are only showing user initials which doesn't tell show submitted the ticket. We should how the full name of submitter at the top somewhere. Also make the initials icon clickable for each message which should open the User details screen. There will be cases where when the ticket is reassigned to different admin, he would want to see who responded to this ticket earlier.

**Comment by MuhammadSarimBader** [comment]
Need backend to send user name in api

**Comment by MuhammadSarimBader** [comment]
other requirement is new update.

**Comment by upliftdawah** [comment]
please see the api reference before making such comments. This field was added way back when you requested. Again this is the usability thing, which seems to be completely missing from the app.

**Comment by MuhammadSarimBader** [comment]
Fixed as discussed

**Comment by upliftdawah** [comment]
verified
