### ISSUE TITLE
[Admin][Task Details] Show assignee name on the scren

### ISSUE THREAD

**Issue by upliftdawah** [upliftdawah/UpliftdawahDocs#45]
We should show assignee name on this screen which should be clickable and open user details screen.

**Comment by MuhammadSarimBader** [comment]
Showing name is feasible but opening user detail from here is another requirement

**Comment by MuhammadSarimBader** [comment]
send me assignee name in the task api currently you are sending assignee ID calling another api to get user info from api is an extra overhead on Front End just send the name I will show it somewhere suitable place in that screen

**Comment by upliftdawah** [comment]
assignee name is already being returned in the get task api, see readme. Please call them new requirements, as this is how it is supposed to be implemented in first place. These are normal things which are implemented in any reasonable app out there. What do you want the admin to do if he wants to call or message the assignee of the task? just think about that. This is what I wanted to be QA'd, the general usability aspect of the app. Now I have to point all these things out.

**Comment by MuhammadSarimBader** [comment]
Shown the assignee name but couldn't make it clickable same reason as I explained on call for tickets.

**Comment by MuhammadSarimBader** [comment]
fixed

**Comment by upliftdawah** [comment]
verified
