### ISSUE TITLE
[Admin][All Users] Filters are empty and causing crash

### ISSUE THREAD

**Issue by upliftdawah** [upliftdawah/UpliftdawahDocs#49]
Login as admin, go to all Users and click on filter, then click on any field, the dropdowns are empty it causes the app to crash.

**Comment by MuhammadSarimBader** [comment]
Fixed

**Comment by upliftdawah** [comment]
pending verification

**Comment by upliftdawah** [comment]
Still empty and crashing

**Comment by upliftdawah** [comment]
verified
