### ISSUE TITLE
[Admin][New Rquests] Default Filters

### ISSUE THREAD

**Issue by upliftdawah** [upliftdawah/UpliftdawahDocs#51]
The current filter box should remain as it is. But following additional filters should always be:
filters: {status: [3], is_email_verified: true}

**Comment by MuhammadSarimBader** [comment]
{
    "code": 200,
    "payload": [
        {
            "id": 1,
            "Value": "Active"
        },
        {
            "id": 2,
            "Value": "Inactive"
        },
        {
            "id": 3,
            "Value": "Unapproved"
        },
        {
            "id": 4,
            "Value": "Unclaimed"
        }
    ]
}

**Comment by MuhammadSarimBader** [comment]
it is already implemented like this

**Comment by MuhammadSarimBader** [comment]
<img width="598" alt="Screen Shot 2020-04-10 at 12 18 25 AM" src="https://user-images.githubusercontent.com/31985211/78932403-d8554d80-7ac0-11ea-95ea-62447659e14b.png">

**Comment by upliftdawah** [comment]
That's wasn't the case when I tested, I will verify it again in the next build

**Comment by upliftdawah** [comment]
verified
