### ISSUE TITLE
[New Muslim] We are missing Educational Material screens

### ISSUE THREAD

**Issue by upliftdawah** [upliftdawah/UpliftdawahDocs#54]
This is one of the most important flows of this app. This should be the first tab opened for new muslims when the login, which should list educational materials for this new muslim. The education material object has a status field for Read/Unread. so all the unread ones should be bold and at the top (use sort order: 'status asc, created_at desc'). Clicking on the educational material should open in a new window and mark it as 'Read'. There is no other action for this screen.

**Comment by MuhammadSarimBader** [comment]
I have tested it the feature is working fine as per our initial discussion read unread handling is also there.

**Comment by upliftdawah** [comment]
What to you mean? where do I see the educational material list? when I login as new muslim i don't see the option

**Comment by MuhammadSarimBader** [comment]
Select your mentor and you may see that screen

**Comment by upliftdawah** [comment]
We don't need it under mentor but instead we should have flat list of all educational material for the user. We have APIs for that and as I said it should be the first screen to open

**Comment by upliftdawah** [comment]
verified
