### ISSUE TITLE
[New Muslim] Remove 'Add User' option for new muslim

### ISSUE THREAD

**Issue by upliftdawah** [upliftdawah/UpliftdawahDocs#55]
We dont need this option for new muslim

**Comment by MuhammadSarimBader** [comment]
Later you will be asking for this as it can happen many times any new muslim wants to add any of his friend who wanted to be guided

**Comment by upliftdawah** [comment]
There is always sign up option for that, lets remove it

**Comment by MuhammadSarimBader** [comment]
Dynamically updating view on run time when hiding and showing add user view took time I had to re apply constraints (Fixed)

**Comment by upliftdawah** [comment]
verified
