### ISSUE TITLE
[Admin] Accept ticket button should keep user on the same screen

### ISSUE THREAD

**Issue by upliftdawah** [upliftdawah/UpliftdawahDocs#56]
Currently when Admin accepts a ticket, we take him back to list ticket screen, which is annoying, we should keep user on the view ticket screen and update the screen accordingly.

**Comment by MuhammadSarimBader** [comment]
Fixed

**Comment by upliftdawah** [comment]
pending verification

**Comment by upliftdawah** [comment]
verified
