### ISSUE TITLE
[New Muslim][View Ticket] Rename buttons

### ISSUE THREAD

**Issue by upliftdawah** [upliftdawah/UpliftdawahDocs#58]
Rename the buttons as below:
'Close' -> 'Close Ticket'
'Hide' -> 'Hide Buttons'

Current texts are confusing.

**Comment by MuhammadSarimBader** [comment]
This is redundancy this is already a ticket section user already know closing means closing the ticket as it is ticket section

**Comment by upliftdawah** [comment]
I had no clue what it meant, please change the text

**Comment by MuhammadSarimBader** [comment]
I have turn Close to Close ticket  and Hide to Hide me

**Comment by upliftdawah** [comment]
verified
