### ISSUE TITLE
[Admin] We should add option to allow change role of a user

### ISSUE THREAD

**Issue by upliftdawah** [upliftdawah/UpliftdawahDocs#59]

**Comment by MuhammadSarimBader** [comment]
There is already an option to change the role of a user. select any user go to details and tap on 3 dot icon

**Comment by upliftdawah** [comment]
With the accept/reject button it doesn't makes sense at all. Please see Issue https://github.com/upliftdawah/UpliftdawahDocs/issues/27 for what buttons should be shown in what cases. Even with these buttons updated, selecting the role from there doesn't make any sense because we are tying up changing the role with changing the status operations which is not needed. Even if we put save button alongside that wouldn't make sense, so it has to be a separate screen or popup.

**Comment by MuhammadSarimBader** [comment]
fixed

**Comment by upliftdawah** [comment]
verified
