### ISSUE TITLE
[Signup] We are not taking input for Role

### ISSUE THREAD

**Issue by upliftdawah** [upliftdawah/UpliftdawahDocs#6]
We were supposed to give a screen before sign up screen to let user select the role he is sign in as (Volunteer, New Muslim or Other). The screen should have three section like buttons, the text in each button/section should be as below:
1. "I am recently reverted to Islam and want to learn more about it"
2. "I want to help Uplift Dawah as a volunteer"
3. "I want submit information of new reverts to Uplift Dawah"

**Comment by MuhammadSarimBader** [comment]
You previously asked me to remove this option and let everyone join as new muslim first then at time of admin confirmation admin will decide the role and four options are given there at the time of confirmation.

**Comment by upliftdawah** [comment]
I don’t remember that conversation, but i do remember asking about the screen i described above on phone call instead of a dropdown. How will the admin who is who, this doesn’t even make sense

**Comment by MuhammadSarimBader** [comment]
Fixed

**Comment by upliftdawah** [comment]
verified
