### ISSUE TITLE
[Volunteer flow][New Muslims List] We should show last contact field instead of phone number

### ISSUE THREAD

**Issue by upliftdawah** [upliftdawah/UpliftdawahDocs#62]
see issue this issue for text and color to show: https://github.com/upliftdawah/UpliftdawahDocs/issues/25

**Comment by MuhammadSarimBader** [comment]
New requirement.

**Comment by upliftdawah** [comment]
No its not, read page 16 of the design doc you guys yourself wrote: https://docs.google.com/document/d/1uhicQrwuhhfKNIFon8TOJFHcJLa_N0eEOCkZn2y4kaQ/edit
This is one of the most important use case for this app

**Comment by MuhammadSarimBader** [comment]
fixed

**Comment by upliftdawah** [comment]
verified
