### ISSUE TITLE
[Volunteer flow][New Muslims list] Open User details screen when click a row

### ISSUE THREAD

**Issue by upliftdawah** [upliftdawah/UpliftdawahDocs#63]
We should show User details screen with at least following buttons on it.
1. Call 
2. Message
3. Post Educational Material (see this issue for what this button will do: https://github.com/upliftdawah/UpliftdawahDocs/issues/64)
4. Meeting Notes (see this issue for what this button will do: https://github.com/upliftdawah/UpliftdawahDocs/issues/65)

**Comment by MuhammadSarimBader** [comment]
fixed

**Comment by upliftdawah** [comment]
verified
