### ISSUE TITLE
[Volunteer flow][New Muslime Details] Post educational meterial button

### ISSUE THREAD

**Issue by upliftdawah** [upliftdawah/UpliftdawahDocs#64]
This button should open the screen to post educational material. It should have large text box and submit button, once it is successfully submitted we should show success message and take user back to user details screen.

**Comment by MuhammadSarimBader** [comment]
This is a complete change of design flow. This is not our understanding for the Volunteer flow.

**Comment by upliftdawah** [comment]
No its not, read page 16 of the design doc you guys yourself wrote: https://docs.google.com/document/d/1uhicQrwuhhfKNIFon8TOJFHcJLa_N0eEOCkZn2y4kaQ/edit
This is one of the most important use case for this app

**Comment by upliftdawah** [comment]
verified
