### ISSUE TITLE
[Volunteer flow][New Muslime Details] Meeting Notes button

### ISSUE THREAD

**Issue by upliftdawah** [upliftdawah/UpliftdawahDocs#65]
This button should open the meeting notes for this new muslim. We don't need to have separate screens for list and view, we can just show the list with full text on the same screen as below. There should be a button to post new meeting notes.

List screen can look list this:
==================================
[mm/dd/yyyy]
I called xyz and spoke to him about islam
-----------------------------------------------
[mm/dd/yyyy]
We met in the cofee shop and I connected him to Imam of the masjid
-----------------------------------------------
[mm/dd/yyyy]
Meeting notes1
======================================

**Comment by MuhammadSarimBader** [comment]
We need to discuss on it

**Comment by MuhammadSarimBader** [comment]
fixed

**Comment by upliftdawah** [comment]
verified
