### ISSUE TITLE
[Bug] Notification screen showing both empty message and the list at the same time

### ISSUE THREAD

**Issue by upliftdawah** [upliftdawah/UpliftdawahDocs#68]
1. Log in when there is no notification.
2. Go to, add user and add new muslim
3. Go back to notification screen, it will show empty notification message and the list at the same time as seen in below screenshot.

![A4199E15-C191-4732-A644-88ADB3E8A073](https://user-images.githubusercontent.com/61668427/88006457-84470580-cac0-11ea-828f-2e2dd43129ee.png)

**Comment by MuhammadSarimBader** [comment]
I have fix this issue
