### ISSUE TITLE
[Signup] User is taken to login screen when email is not yet verified

### ISSUE THREAD

**Issue by upliftdawah** [upliftdawah/UpliftdawahDocs#7]
I signed up as new user and haven't yet verified my email. I was being shown the email verification screen (which is correct) but as soon as I closed the app and reopen it took me back to login screen. We were suppose to store this information somewhere on the phone so that if the user close the app and reopens it will take it back to email verification screen, until the user 'Cancel' button.

**Comment by MuhammadSarimBader** [comment]
It's fine I tried to keep the flow simple in code base so we could have less ambiguity. As user tries to sign in or sign up again it will take him to email verification. As sign up is not frequent process for any user providing this extra UX experience will increase more complexity in code base. May open run time critical ambiguity.

**Comment by upliftdawah** [comment]
I don’t like it but i am fine closing this issue

**Comment by upliftdawah** [comment]
verified
