### ISSUE TITLE
[Bug] View meeting notes screen is not filtering by 'created_for'

### ISSUE THREAD

**Issue by upliftdawah** [upliftdawah/UpliftdawahDocs#71]
When I see meeting notes for a new muslim, it shows notes for all new muslims, seems like we are not passing anything in created_for filter. I have seen this on iphone, not sure if this also the case for android.

**Comment by MuhammadSarimBader** [comment]
<img width="387" alt="Screen Shot 2020-07-23 at 8 39 57 AM" src="https://user-images.githubusercontent.com/31985211/88250430-0d2c8f80-ccc1-11ea-8b95-acf8e3e8b149.png">

**Comment by MuhammadSarimBader** [comment]
I have verified correct user id is passing in created for. Meeting notes are being fetched by two roles, One is admin and second is Volunteers. Now in case of volunteers, volunteers can only see their own notes that is why I am applying created by in filter. But in case of admin this created by id belongs to admin role so in this case maybe backend is giving all the notes. please verify it from backend.

**Comment by upliftdawah** [comment]
It should be 'filters' not filter. please also check if we are using 'filters' everywhere else as well.

**Comment by SM-Ahsan** [comment]
Fixed and verified in android.
