### ISSUE TITLE
[Android] Wrong sections on notification screen

### ISSUE THREAD

**Issue by upliftdawah** [upliftdawah/UpliftdawahDocs#75]
Android app shows un attended new muslims section even though it is empty, and it doesnt show the pending membership request where there is one item, see the iphone screenshot and compare it with andriod one to see the difference 
iphone screen shot:
![A3C6878C-C600-48CA-B6B9-06473BE207EF](https://user-images.githubusercontent.com/61668427/104547460-74c5f680-55e3-11eb-9e99-ef64afaa56b7.jpeg)

android screenshot 
![CEB5C711-D05D-465A-B219-F97EDCF711AB](https://user-images.githubusercontent.com/61668427/104547516-97580f80-55e3-11eb-93fb-e38c08fd3d86.jpeg)

**Comment by SM-Ahsan** [comment]
FIXED
