### ISSUE TITLE
[Android]“Notes” button is now showing when going from new shahadah full list

### ISSUE THREAD

**Issue by upliftdawah** [upliftdawah/UpliftdawahDocs#77]
if you click new muslim in the new shahadah section of notification screen then it shows “Notes” button on the new muslim screen but if you first click “show more” on new shahadah and from full new muslim list tap a new muslim it doesnt show Notes button

see screen shot
![1A854665-3EF9-40CF-8CCE-6519FABEF281](https://user-images.githubusercontent.com/61668427/104548249-447f5780-55e5-11eb-91b3-87dff4338225.jpeg)

**Comment by SM-Ahsan** [comment]
FIXED
