### ISSUE TITLE
[Android] New muslim list only shows 4 items while there are many more

### ISSUE THREAD

**Issue by upliftdawah** [upliftdawah/UpliftdawahDocs#78]
On new muslims list it is only showing 4 items while there are many more see screen shot
![AF44BE11-A297-475B-807E-EA2246D32897](https://user-images.githubusercontent.com/61668427/104548427-a475fe00-55e5-11eb-9d5a-ef8481a5b962.jpeg)

**Comment by SM-Ahsan** [comment]
FIXED
