### ISSUE TITLE
[Android] Tickets screen keeps loading forever 

### ISSUE THREAD

**Issue by upliftdawah** [upliftdawah/UpliftdawahDocs#79]
on tickets list screen the spinner doesnt go away it keeps loading 
![8E84E419-97F0-4BCB-B9E2-9DA528E1F1BF](https://user-images.githubusercontent.com/61668427/104548546-e56e1280-55e5-11eb-9643-c34ed8af6c55.jpeg)

**Comment by SM-Ahsan** [comment]
FIXED
