### ISSUE TITLE
[Admin] After login we should open Notification screen be default

### ISSUE THREAD

**Issue by upliftdawah** [upliftdawah/UpliftdawahDocs#8]
Right now it opens Volunteers screen, we should instead open notification screen
1. Notification Screen should be first
2. When there is no notifications for Admin it should have this text 
Hurray!! you are all caught up" <- Heading
There are no pending notifications at this time

**Comment by MuhammadSarimBader** [comment]
I will make it app first screen in admin flow

**Comment by upliftdawah** [comment]
pending verification

**Comment by MuhammadSarimBader** [comment]
Fixed

**Comment by upliftdawah** [comment]
verified
