### ISSUE TITLE
[Android] App reloads every time when you switch between apps

### ISSUE THREAD

**Issue by upliftdawah** [upliftdawah/UpliftdawahDocs#80]
Iphone app remembers the screen you are on when you switch apps but android app always reloads and go back to notification screen when switching the apps

**Comment by SM-Ahsan** [comment]
I tested on other device, it works fine and doesn't reload the app when brought from background to foreground. This has to do with how much RAM the device has. That device has 2 GB of RAM, which is pretty "weak" these days. With that little RAM, the OS has to aggressively unload apps from memory to make room for the next app you're opening (which then needs to load into RAM). A device with more RAM won't need to do this as much.
