### ISSUE TITLE
[Android] 'Assign Mentors' is showing up in unwanted places

### ISSUE THREAD

**Issue by upliftdawah** [upliftdawah/UpliftdawahDocs#87]
Please see iphone app to see where this button should be displayed. We should only show it there.

**Comment by SM-Ahsan** [comment]
Please explain this case here as I can't figure out through iphone app.

**Comment by upliftdawah** [comment]
I think I saw this buttong being shown in android on some places where it should not be, please make sure following 2 things, if it is happening that way then feel free to close the ticket
1. the button should be displayed only where we are displaying it in iphone 
2. it should only be displayed in front of new muslim users not for any other roles
